name             'lvsf-opsworks-php-cookbook'
maintainer       'Spain Train'
maintainer_email 'spain@livesafemobile.com'
license          'All rights reserved'
description      'Installs/Configures lvsf-opsworks-php-cookbook'
long_description 'Installs/Configures lvsf-opsworks-php-cookbook'
version          '1.0.5'

depends 'ohai'
depends 'apt'
depends 'php5-fpm'
depends 'ohai'
depends 'nginx'
